# Generated by Django 2.1.4 on 2019-04-17 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='core/logos')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('edicion', models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='core.Edicion', verbose_name='Edicion')),
            ],
            options={
                'verbose_name': 'organizador',
                'verbose_name_plural': 'organizadores',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Organizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'tipo_organizador',
                'verbose_name_plural': 'tipos_organizadores',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AddField(
            model_name='organizador',
            name='tipo_organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Tipo_Organizador', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='organizador',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
