"""
Django settings for uvmadmin project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=1a(6*&@=5c09cv8c3xt29wg)nh84^fesyed4f*v7!i#lo1izl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Aplicacion de registro de usuarios
    'registration',                 # La ponemos al principio para darle prioridad ante todo
    # Aplicaciones de Django
    'django.contrib.admin',
    'django.contrib.auth',          # Autenticación de usuarios
    'django.contrib.contenttypes',  # Permite asociar permisos a los modelos
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps de terceros
    'ckeditor',    
    'gallery',
    'bootstrap_modal_forms',        # Formularios Modales
    'widget_tweaks',                # Formularios Modales
    # Aplicaciones Propias de uvmadmin
    'core',
    'noticias.apps.NoticiasConfig',
    'alumnos',
    'ponentes',
    'materias',
    'matriculas',
    'pages',
    'universidad',
]
 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',     # Gestiona sesiones a través de solicitues
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Asocia usuarios con peticiones utilizando sesiones
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'uvmadmin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'core_tags': 'core.templatetags.core.core_tags',                
                'gallery_tags': 'gallery.templatetags.gallery.gallery_tags',
            }
        },
    },
]

WSGI_APPLICATION = 'uvmadmin.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'uvm_v2',
            'USER': 'root',
            'PASSWORD': 'Pepechola2011',
            'HOST': 'localhost',
            'PORT': '',
#            'HOST': '192.168.21.18',
#            'PORT': '3306',
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
    },
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Redireccionamiento cuando el usuario se autentifica correctamente y cuando sale
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'login'

# MFG - Media config
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Constante para la paginación en el sitio web
BASE_PAGE_BY = 10

# --------------------------------
# Editor de texto: CKEDITOR
# --------------------------------
CKEDITOR_CONFIGS = {
    'default': {
        'height': 300,
        'width': 900,
    },
    
}
CKEDITOR_UPLOAD_PATH = "uploads/"

# Emails
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
    EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails")
else:
    # Aquí hay que configurar un email real para producción
    pass