# Generated by Django 2.1.4 on 2019-04-12 07:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        ('ponentes', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apunte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_apunte', models.CharField(max_length=100, verbose_name='Descripción')),
                ('fichero', models.FileField(blank=True, null=True, upload_to='materias/apuntes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'apunte',
                'verbose_name_plural': 'apuntes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, verbose_name='Código')),
                ('denominacion', models.CharField(max_length=200, verbose_name='Denominacion')),
                ('lugar', models.CharField(default='', max_length=200, verbose_name='Lugar Celebración')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='materias')),
                ('programa', models.FileField(blank=True, null=True, upload_to='materias')),
                ('finicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('ffin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('hinicio', models.TimeField(blank=True, null=True, verbose_name='Hora inicio')),
                ('hfin', models.TimeField(blank=True, null=True, verbose_name='Hora fin')),
                ('creditos', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Créditos')),
                ('horas', models.SmallIntegerField(default=0, verbose_name='Horas')),
                ('observaciones', ckeditor.fields.RichTextField(verbose_name='Observaciones')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe Normal')),
                ('importe_reducido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe Reducido')),
                ('plazas', models.SmallIntegerField(default=0, verbose_name='Plazas')),
                ('descuento', models.BooleanField(default=False, verbose_name='Descuento')),
                ('plazas_dto', models.SmallIntegerField(default=0, verbose_name='Plazas con Descuento')),
                ('plazas_dto_ocupadas', models.SmallIntegerField(default=0, verbose_name='Plazas con Descuento Ocupadas')),
                ('otracuenta', models.BooleanField(default=False, verbose_name='Otro Número de Cuenta')),
                ('cuenta', models.CharField(default='Ir al enlace que aparece en la información del curso para REGISTRARSE y PAGAR. (Cada curso se abona de forma individual).', max_length=200, verbose_name='Cuenta')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
                ('dirigido', models.CharField(default='Todos los públicos', max_length=200, verbose_name='Dirigido a')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('edicion', models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='core.Edicion', verbose_name='Edición')),
                ('ponente', models.ManyToManyField(blank=True, to='ponentes.Ponente', verbose_name='Ponentes')),
            ],
            options={
                'verbose_name': 'materia',
                'verbose_name_plural': 'materias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Ponencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=200, verbose_name='Denominacion')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Materia', verbose_name='Materia')),
                ('ponente', models.ManyToManyField(blank=True, to='ponentes.Ponente', verbose_name='Ponentes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'ponencia',
                'verbose_name_plural': 'ponencias',
                'ordering': ['materia', 'denominacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_materia', models.CharField(max_length=100, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'tipomateria',
                'verbose_name_plural': 'tiposmaterias',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='materia',
            name='tipo_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.TipoMateria', verbose_name='Tipo Materia'),
        ),
        migrations.AddField(
            model_name='materia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='apunte',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.Materia', verbose_name='Materia'),
        ),
        migrations.AddField(
            model_name='apunte',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
