# Generated by Django 2.1.4 on 2019-04-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponencia',
            name='fin',
        ),
        migrations.AddField(
            model_name='ponencia',
            name='hfin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Fin'),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='hinicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Inicio'),
        ),
    ]
