# Generated by Django 2.1.4 on 2019-04-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0004_auto_20190412_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='descuento',
            field=models.ManyToManyField(blank=True, to='materias.Descuento', verbose_name='Descuentos'),
        ),
    ]
