# Generated by Django 2.1.4 on 2019-04-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0005_materia_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=10, verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='materias/imagenes'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='programa',
            field=models.FileField(blank=True, null=True, upload_to='materias/programas'),
        ),
    ]
