# Generated by Django 2.1.4 on 2019-04-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_edicion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('edicion', models.SmallIntegerField(default=0, verbose_name='Año Edición')),
                ('activa', models.BooleanField(default=False, verbose_name='Edición Activa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'edicion',
                'verbose_name_plural': 'ediciones',
                'ordering': ['-created'],
            },
        ),
    ]
